# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/jupyterhub-team-compass/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "24"
    python: "3.14"
  jobs:
    install:
      - python -m pip install -r docs/requirements.txt
    build:
      html:
        - mkdir -p "$READTHEDOCS_OUTPUT"
        - cd docs/ && python -m jupyter book build --ci --html
        - cp -r docs/_build/html "$READTHEDOCS_OUTPUT"