# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/jupyterhub-team-compass/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
    nodejs: "24"
  jobs:
    install:
      - pip install jupyter-book==2
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - cd docs/ && jupyter book build --html
        - cp -a docs/_build/html/. "$READTHEDOCS_OUTPUT/html"
